apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: backend-pipeline-ci-with-sonar
  namespace: default
spec:
  description: |
    Backend CI Pipeline with SonarQube - 코드 스캔 후 이미지 빌드 및 Harbor 푸시
    SonarQube 스캔에서 취약점이 발견되면 파이프라인이 실패합니다.
  params:
  - name: git-url
    description: Git repository URL
    default: https://github.com/dprxrx/error-archive.git
    type: string
  - name: git-revision
    description: Git branch or tag
    default: main
    type: string
  - name: docker-image
    description: Docker image name (e.g., repo/backend:tag)
    default: 192.168.0.169:443/project/error-archive-backend:latest
    type: string
  - name: registry-url
    description: Docker registry URL
    default: 192.168.0.169:443
    type: string
  - name: registry-username
    description: Docker registry username
    default: admin
    type: string
  - name: registry-password
    description: Docker registry password
    default: Harbor12345
    type: string
  - name: sonarqube-url
    description: SonarQube 서버 URL
    default: http://sonarqube.sonarqube:9000
    type: string
  - name: sonarqube-project-key
    description: SonarQube 프로젝트 키
    default: error-archive-backend
    type: string
  - name: sonarqube-project-name
    description: SonarQube 프로젝트 이름
    default: Error Archive Backend
    type: string
  workspaces:
  - name: shared-workspace
    description: Shared workspace for all tasks
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    params:
    - name: git-url
      value: $(params.git-url)
    - name: git-revision
      value: $(params.git-revision)
    workspaces:
    - name: source
      workspace: shared-workspace
  
  # SonarQube 토큰 읽기
  - name: read-sonarqube-token
    runAfter:
    - git-clone
    taskRef:
      name: read-sonarqube-token
    params:
    - name: secret-name
      value: sonarqube-token-backend
    - name: secret-key
      value: token
  
  # SonarQube 스캔 (git-clone 이후, docker-build-and-push 이전)
  - name: sonarqube-scan
    runAfter:
    - read-sonarqube-token
    taskRef:
      name: sonarqube-scan
    params:
    - name: sonarqube-url
      value: $(params.sonarqube-url)
    - name: sonarqube-token
      value: $(tasks.read-sonarqube-token.results.token)
    - name: project-key
      value: $(params.sonarqube-project-key)
    - name: project-name
      value: $(params.sonarqube-project-name)
    - name: source-path
      value: backend
    - name: language
      value: js
    workspaces:
    - name: source
      workspace: shared-workspace
  
  # Docker 빌드 및 푸시 (SonarQube 스캔 성공 후)
  - name: docker-build-and-push
    runAfter:
    - sonarqube-scan
    taskRef:
      name: docker-build-and-push
    params:
    - name: image
      value: $(params.docker-image)
    - name: registry-url
      value: $(params.registry-url)
    - name: registry-username
      value: $(params.registry-username)
    - name: registry-password
      value: $(params.registry-password)
    - name: dockerfile-path
      value: "Dockerfile"
    - name: build-context
      value: "backend"
    workspaces:
    - name: source
      workspace: shared-workspace

