#!/bin/bash
# 프로젝트 시연 전체 시나리오

echo "=========================================="
echo "  프로젝트 시연: 가을 → 겨울 테마 전환"
echo "=========================================="
echo ""

echo "📋 시연 순서:"
echo ""
echo "1단계: 가을 테마 확인"
echo "  - 웹사이트 접속 시 가을 테마 (낙엽 효과) 표시"
echo "  - 배경: 갈색/금색 그라데이션"
echo ""
echo "2단계: 겨울 테마로 전환"
echo "  방법 1: 브라우저 콘솔에서"
echo "    changeTheme('winter')"
echo ""
echo "  방법 2: 관리자 페이지에서 (구현 예정)"
echo ""
echo "3단계: 로그인"
echo "  - 일반 로그인 또는 소셜 로그인"
echo "  - 로그인 후 list.html로 이동"
echo ""
echo "4단계: 이벤트 배너 확인"
echo "  - 상단에 '겨울 맞이 이벤트' 배너 표시"
echo "  - '참여하기' 버튼 클릭"
echo ""
echo "5단계: 룰렛 돌리기"
echo "  - roulette.html 페이지에서"
echo "  - '룰렛 돌리기' 버튼 클릭"
echo "  - 결과 확인 (꽝, 피자, 치킨, 삼겹살, 소고기)"
echo "  - 결과는 자동으로 저장됨"
echo ""
echo "6단계: 히스토리 확인"
echo "  - 룰렛 페이지 하단에 나의 룰렛 결과 표시"
echo ""
echo "=========================================="
echo "  롤백 방법"
echo "=========================================="
echo ""
echo "테마 롤백:"
echo "  브라우저 콘솔: changeTheme('autumn')"
echo ""
echo "이벤트 배너 숨김 해제:"
echo "  localStorage.removeItem('eventBannerClosed')"
echo "  location.reload()"
echo ""

