#!/bin/bash

# SonarQube 토큰 생성 가이드
# 이 스크립트는 SonarQube UI에서 토큰을 생성하는 방법을 안내합니다.

echo "=========================================="
echo "  SonarQube 토큰 생성 가이드"
echo "=========================================="
echo ""
echo "1. SonarQube 접속:"
echo "   kubectl port-forward svc/sonarqube -n sonarqube 9000:9000"
echo "   브라우저에서 http://localhost:9000 접속"
echo ""
echo "2. 로그인:"
echo "   기본 계정: admin / admin"
echo "   (첫 로그인 시 비밀번호 변경 필요)"
echo ""
echo "3. 토큰 생성:"
echo "   - 우측 상단 프로필 아이콘 클릭"
echo "   - 'My Account' 선택"
echo "   - 'Security' 탭 선택"
echo "   - 'Generate Token' 클릭"
echo "   - 토큰 이름 입력 (예: tekton-ci)"
echo "   - 'Generate' 클릭"
echo "   - 생성된 토큰을 복사 (한 번만 표시됨!)"
echo ""
echo "4. 프로젝트 생성:"
echo "   - 'Projects' > 'Create Project'"
echo "   - 'Manually' 선택"
echo "   - Project Key: error-archive-backend (또는 frontend)"
echo "   - Display Name: Error Archive Backend (또는 Frontend)"
echo ""
echo "5. 토큰을 Kubernetes Secret에 저장:"
echo "   kubectl create secret generic sonarqube-token \\"
echo "     --from-literal=token=YOUR_TOKEN_HERE \\"
echo "     --namespace=default"
echo ""
echo "=========================================="

